//! Builds MPC 1.3.1 as a static library from the pristine upstream source,
//! using only the Zig build system (no ./configure, no make).
//!
//! MPC sits on top of GMP and MPFR; it just needs their installed headers on
//! its include path (supplied by linking the from-source libgmp/libmpfr) plus
//! a hand-written config.h. Only logging.c is dropped (it is the dynamic-load
//! logging wrapper, not part of the library proper).
//!
//! Linked into GCC's cc1 so the toolchain can target a host (Windows/macOS)
//! that has no system libmpc.
//! SPDX-License-Identifier: LGPL-3.0-or-later

const std = @import("std");

/// Build a static libmpc.a against the from-source `gmp_lib`/`mpfr_lib`.
/// `host_target` is the toolchain's host (where cc1 runs).
pub fn addMpc(
    b: *std.Build,
    mpc_root: std.Build.LazyPath,
    gmp_lib: *std.Build.Step.Compile,
    mpfr_lib: *std.Build.Step.Compile,
    host_target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
) *std.Build.Step.Compile {
    const src = mpc_root.path(b, "src");

    const gen = b.addWriteFiles();
    _ = gen.add("config.h", configH());
    const gen_dir = gen.getDirectory();

    const lib = b.addLibrary(.{
        .linkage = .static,
        .name = "mpc",
        .root_module = b.createModule(.{
            .target = host_target,
            .optimize = optimize,
            .link_libc = true,
        }),
    });
    const mod = lib.root_module;

    mod.addIncludePath(gen_dir);
    mod.addIncludePath(src);
    // mpfr_lib already links gmp_lib and propagates both headers, but link gmp
    // explicitly so libmpc.a's archive index records the dependency too.
    mod.linkLibrary(mpfr_lib);
    mod.linkLibrary(gmp_lib);

    mod.addCSourceFiles(.{
        .root = src,
        .files = collectSources(b, mpc_root),
        .flags = &.{"-DHAVE_CONFIG_H"},
    });

    if (host_target.result.os.tag != .windows) mod.linkSystemLibrary("m", .{});

    lib.installHeader(src.path(b, "mpc.h"), "mpc.h");
    return lib;
}

/// The library sources, parsed from src/Makefile.am's libmpc_la_SOURCES.
/// logging.c is dropped (dynamic-load logging wrapper, not in the library).
fn collectSources(b: *std.Build, mpc_root: std.Build.LazyPath) []const []const u8 {
    const makefile = mpc_root.path(b, "src/Makefile.am").getPath(b);
    const out = b.run(&.{
        "sh", "-c",
        b.fmt(
            "sed -n '/^libmpc_la_SOURCES/,/balls.c/p' '{s}' | grep -oE '[a-zA-Z0-9_]+\\.c' | sort -u",
            .{makefile},
        ),
    });

    var names: std.ArrayList([]const u8) = .empty;
    var it = std.mem.tokenizeScalar(u8, out, '\n');
    while (it.next()) |line| {
        const name = std.mem.trim(u8, line, " \t\r");
        if (name.len == 0) continue;
        if (std.mem.eql(u8, name, "logging.c")) continue;
        names.append(b.allocator, b.dupe(name)) catch @panic("OOM");
    }
    return names.toOwnedSlice(b.allocator) catch @panic("OOM");
}

fn configH() []const u8 {
    return
    \\/* Generated by gcc-cross-zig: MPC 1.3.1. */
    \\#define PACKAGE "mpc"
    \\#define PACKAGE_NAME "mpc"
    \\#define PACKAGE_VERSION "1.3.1"
    \\#define VERSION "1.3.1"
    \\#define LT_OBJDIR ".libs/"
    \\#define STDC_HEADERS 1
    \\#define HAVE_STDINT_H 1
    \\#define HAVE_INTTYPES_H 1
    \\#define HAVE_STDLIB_H 1
    \\#define HAVE_STRING_H 1
    \\#define HAVE_SYS_TYPES_H 1
    \\#define HAVE_LOCALECONV 1
    \\#define HAVE_SETLOCALE 1
    \\#define HAVE_INTPTR_T 1
    \\#define HAVE_LIBM 1
    \\#define HAVE_COMPLEX_H 1
    \\
    ;
}
