//! Builds MPFR 4.2.1 as a static library from the pristine upstream source,
//! using only the Zig build system (no ./configure, no make).
//!
//! MPFR is built against the public GMP header only (no gmp-impl.h), so it
//! just needs libgmp's installed gmp.h on its include path -- supplied by
//! linking the from-source libgmp produced by gmp.zig. The generic thresholds
//! header (src/generic/mparam.h) is used unchanged, and the otherwise
//! configure-generated get_patches.c is produced by the upstream shell script
//! (the PATCHES list is empty, so it just reports no patches).
//!
//! Linked into GCC's cc1 so the toolchain can target a host (Windows/macOS)
//! that has no system libmpfr.
//! SPDX-License-Identifier: LGPL-3.0-or-later

const std = @import("std");

/// Build a static libmpfr.a against the from-source `gmp_lib`. `host_target`
/// is the toolchain's host (where cc1 runs).
pub fn addMpfr(
    b: *std.Build,
    mpfr_root: std.Build.LazyPath,
    gmp_lib: *std.Build.Step.Compile,
    host_target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
) *std.Build.Step.Compile {
    const src = mpfr_root.path(b, "src");

    // Generated include dir: hand-written config.h. mparam.h is found via the
    // src/generic include path, mpfr.h/mpfr-impl.h live in src/.
    const gen = b.addWriteFiles();
    _ = gen.add("config.h", configH(b, host_target));
    const gen_dir = gen.getDirectory();

    // get_patches.c is normally a build-time generated source. Run the upstream
    // shell script over the (empty) PATCHES list to produce it.
    const patches_c = b.run(&.{
        "sh",
        mpfr_root.path(b, "tools/get_patches.sh").getPath(b),
        mpfr_root.path(b, "PATCHES").getPath(b),
    });
    const patches_file = gen.add("get_patches.c", patches_c);

    const lib = b.addLibrary(.{
        .linkage = .static,
        .name = "mpfr",
        .root_module = b.createModule(.{
            .target = host_target,
            .optimize = optimize,
            .link_libc = true,
        }),
    });
    const mod = lib.root_module;

    mod.addIncludePath(gen_dir);
    mod.addIncludePath(src);
    mod.addIncludePath(src.path(b, "generic"));
    // Pulls in libgmp's installed gmp.h and links the static archive.
    mod.linkLibrary(gmp_lib);

    const flags = [_][]const u8{"-DHAVE_CONFIG_H"};
    mod.addCSourceFile(.{ .file = patches_file, .flags = &flags });
    mod.addCSourceFiles(.{
        .root = src,
        .files = collectSources(b, mpfr_root),
        .flags = &flags,
    });

    if (host_target.result.os.tag != .windows) mod.linkSystemLibrary("m", .{});

    lib.installHeader(src.path(b, "mpfr.h"), "mpfr.h");
    lib.installHeader(src.path(b, "mpf2mpfr.h"), "mpf2mpfr.h");
    return lib;
}

/// The library sources, parsed from src/Makefile.am's libmpfr_la_SOURCES.
/// mpfr-mini-gmp.c is dropped (only used with --with-mini-gmp); get_patches.c
/// is added separately as a generated source.
fn collectSources(b: *std.Build, mpfr_root: std.Build.LazyPath) []const []const u8 {
    const makefile = mpfr_root.path(b, "src/Makefile.am").getPath(b);
    const out = b.run(&.{
        "sh", "-c",
        b.fmt(
            "sed -n '/^libmpfr_la_SOURCES/,/^nodist/p' '{s}' | grep -oE '[a-zA-Z0-9_-]+\\.c' | sort -u",
            .{makefile},
        ),
    });

    var names: std.ArrayList([]const u8) = .empty;
    var it = std.mem.tokenizeScalar(u8, out, '\n');
    while (it.next()) |line| {
        const name = std.mem.trim(u8, line, " \t\r");
        if (name.len == 0) continue;
        if (std.mem.eql(u8, name, "mpfr-mini-gmp.c")) continue;
        names.append(b.allocator, b.dupe(name)) catch @panic("OOM");
    }
    return names.toOwnedSlice(b.allocator) catch @panic("OOM");
}

fn configH(b: *std.Build, host_target: std.Build.ResolvedTarget) []const u8 {
    const t = host_target.result;
    // Long double layout decides which set_ld/get_ld conversion path compiles.
    const ldouble: []const u8 = switch (t.cpu.arch) {
        .x86_64, .x86 => "#define HAVE_LDOUBLE_IEEE_EXT_LITTLE 1",
        .aarch64 => if (t.os.tag == .macos)
            "#define HAVE_LDOUBLE_IS_DOUBLE 1"
        else
            "#define HAVE_LDOUBLE_IEEE_QUAD_LITTLE 1",
        else => "/* long double: generic fallback */",
    };
    return b.fmt(
        \\/* Generated by gcc-cross-zig: MPFR 4.2.1, generic thresholds. */
        \\#define PACKAGE_NAME "MPFR"
        \\#define PACKAGE_VERSION "4.2.1"
        \\#define VERSION "4.2.1"
        \\#define LT_OBJDIR ".libs/"
        \\#define STDC_HEADERS 1
        \\#define HAVE_STDINT_H 1
        \\#define HAVE_INTTYPES_H 1
        \\#define HAVE_STDLIB_H 1
        \\#define HAVE_STRING_H 1
        \\#define HAVE_STDARG 1
        \\#define HAVE_SYS_TYPES_H 1
        \\#define HAVE_LOCALE_H 1
        \\#define HAVE_WCHAR_H 1
        \\#define HAVE_LONG_LONG 1
        \\#define HAVE_INTMAX_T 1
        \\#define HAVE_UINTPTR_T 1
        \\#define HAVE_VA_COPY 1
        \\#define HAVE_SETLOCALE 1
        \\#define HAVE_STRUCT_LCONV_DECIMAL_POINT 1
        \\#define HAVE_STRUCT_LCONV_THOUSANDS_SEP 1
        \\#define HAVE_ATTRIBUTE_MODE 1
        \\#define HAVE_BUILTIN_UNREACHABLE 1
        \\#define HAVE_DOUBLE_IEEE_LITTLE_ENDIAN 1
        \\#define HAVE_LITTLE_ENDIAN 1
        \\#define MPFR_HAVE_FESETROUND 1
        \\#define MPFR_HAVE_INTMAX_T 1
        \\#define MPFR_LONG_WITHIN_LIMB 1
        \\#define MPFR_TUNE_CASE "default"
        \\{s}
        \\
    , .{ldouble});
}
